### ISSUE TITLE
Failed to fire an event because of console.dir()

### ISSUE THREAD

**Issue by kamtungc** [radiantmediaplayer/rmp-vast#51] opened 2022-07-27 17:51 UTC
In v6.0.0, createApiEvent() in utils.js is below
  static createApiEvent(event) {
    if (Array.isArray(event)) {
      event.forEach(currentEvent => {
        if (currentEvent) {
          if (this.debug) {
            FW.log(currentEvent);
          }
          FW.createStdEvent(currentEvent, this.container);
        }
      });
    } else if (event) {
      if (this.debug) {
        FW.log(event);
      }
      FW.createStdEvent(event, this.container);
    }
  }

In v7.1.0, createApiEvent() in utils.js is below
   static createApiEvent(event) {
    if (Array.isArray(event)) {
      event.forEach(currentEvent => {
        if (currentEvent) {
          console.dir(currentEvent);
          FW.createStdEvent(currentEvent, this.container);
        }
      });
    } else if (event) {
      console.dir(event);
      FW.createStdEvent(event, this.container);
    }
  }

In v7.1.0, I got an error "Could not complete the operation due to error 80020101." for an event, such as adfirstquartile.

After I removed both `console.dir(currentEvent);` and `console.dir(event);`, I didn't have an error.

**Comment by radiantmediaplayer** [comment] 2022-07-27 19:09
I cannot reproduce this issue on our side. Can you provide a code sample that reproduces this issue? What browser and what os are your testing on?

**Comment by kamtungc** [comment] 2022-07-27 20:40
I am using UWP WebView.

**Comment by radiantmediaplayer** [comment] 2022-07-28 15:47
This should be fixed in [7.2.0](https://github.com/radiantmediaplayer/rmp-vast/releases/tag/v7.2.0)

**Closed by radiantmediaplayer** 2022-07-28 15:47 UTC
